version: '2'
services:
    app:
        build: .
        depends_on:
          - cassandra
        volumes:
            - .:/app
        command: npm test
        environment:
            - NODE_ENV=docker
            - CI=true
            - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
            - TRAVIS=${TRAVIS}
    cassandra:
      image: cassandra:latest
      environment:
          - CASSANDRA_START_RPC=true
