version: '2'
services:
    app:
        build: .
        depends_on:
          - cassandra
        volumes:
            - .:/app
        command: npm test
        environment:
            - NODE_ENV=docker
            - CI=true
            - TRAVIS_REPO_SLUG=blugavere/cassandra-repository
            - TRAVIS=true
            - COVERALLS_SERVICE_NAME=travis-ci
            - COVERALLS_REPO_TOKEN=${COVERALLS}
    cassandra:
      image: cassandra:latest
      environment:
          - CASSANDRA_START_RPC=true
